### ISSUE TITLE
Items are no longer collected when an enchanted furnace is broken

### ISSUE THREAD

**Issue by aurel85** [Jikoo/EnchantableBlocks#11]
Hi,

When breaking an enchanted oven, the items contained in the oven are not recovered as shown in this video.
I am using Paper 1.16.3 and the latest version of the plugin.

Video : https://drive.google.com/file/d/1KqXRbWZS55ygO5OoyJWHQrqx1oeUTZ9b/view

**Comment by aurel85** [comment]
Hi, will the version with this bug corrected be released soon ? Because it looks corrected but I have nothing published on bukkit.

**Comment by Jikoo** [comment]
You can abuse JitPack for a CI for most Maven-based projects, https://jitpack.io/com/github/Jikoo/EnchantableBlocks/c143e54434/EnchantableBlocks-c143e54434.jar should work.

**Comment by aurel85** [comment]
Thank you !

**Comment by aurel85** [comment]
Hi, after tests the problem is not solved :/

**Comment by Jikoo** [comment]
Unfortunately this appears to be a Paper... I don't want to say bug, but it is a quirk. Spigot does not capture all drops properly, so prior to Paper 197 inventory contents were not included in drop lists and also were not prevented from dropping by `BlockBreakEvent#setDropItems`. Since Paper changed the behavior, I need to rethink my approach or risk dupe bugs on Spigot.

**Comment by Jikoo** [comment]
Had some time and looked into this. It may actually require Paper-specific code thanks to the inconsistencies introduced by https://github.com/PaperMC/Paper/commit/d802a50a9a7a898178269586a7bee8725c19eff4. Prior to this patch (i.e. Spigot behavior), setting `BlockBreakEvent#setItemDrops` to false would still drop inventory contents, because while they're dropped by breaking the block they are not the drops of the block itself. However, this patch does not add the drops it now considers part of the block's drops to `Block#getDrops`. Unfortunately, if Paper ever changes this behavior again, this will result in dupe bugs with the current implementation. The only way I can see this working safely is if I do some hackjob thing where I spread the dropping process over multiple events.

**Comment by Jikoo** [comment]
https://jitpack.io/com/github/Jikoo/EnchantableBlocks/0dc9e92872/EnchantableBlocks-0dc9e92872.jar should work, includes the described hack to avoid Paper-specific code.

**Comment by aurel85** [comment]
Everything is ok, thank you !
