### ISSUE TITLE
Bugs with 2.0.1

### ISSUE THREAD

**Issue by aurel85** [Jikoo/EnchantableBlocks#3]
Hi,

In the console when a enchanted furnace is activated : https://pastebin.com/a06uqxEa

The bug with charcoal (2.0.0) is resolved but the enchantments doesn't work.

My furnace has Efficiency V, Unbreaking III, Fortune III and Silk Touch.

I use PaperSpigot 1.13.2.

**Comment by Jikoo** [comment]
If you would please, try [EnchantableBlocks 2.0.2-SNAPSHOT](https://github.com/Jikoo/EnchantableBlocks/files/2776231/EnchantableBlocks.zip).
The debug will probably be quite spammy, but I'm interested in finding out if this is a default Minecraft recipe that's screwed up or if a plugin isn't playing nice.

**Comment by Jikoo** [comment]
I don't mess with experience currently, that's just due to the fact that a single smelt of iron yields .7 to .1 from stone. Fortune doesn't affect the experience gain in 1.13 due to changes in how experience is handled, though I suppose I could revert that behavior to match 1.12 and lower. That said, furnaces storing exp would make fortune even more incredibly broken. Not sure how I feel about it in terms of balance, what do you think?

Yeah, CoralStay appears to be the issue. I guess I'll leave the exception catching, but the author should really consider revisiting their [recipe creation](https://github.com/ryandw11/CoralStay/blob/master/src/me/ryandw11/coralstay/CoralStay.java#L76).
There are currently no checks made to ensure the materials exist, and the NamespacedKey being created should be using the namespace `coralstay`, instead of `minecraft` and prefixing every recipe with `coralstay_`. 

This is more of a Spigot issue, the server shouldn't be accepting problematic recipes. From what I can tell, the invalid input is "fine" when [added](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/inventory/CraftRecipe.java#21) to the crafting manager. Then, when the actual choice list is rebuilt converting back from NMS to Bukkit, the invalid recipe is not added, yielding an empty input list, which [results](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/inventory/CraftRecipe.java#35) in a null RecipeChoice.

**Comment by Jikoo** [comment]
Okay, I've also opened [SPIGOT-4587](https://hub.spigotmc.org/jira/browse/SPIGOT-4587) for the CB end.
For now, here's a build without the debug message: [EnchantableBlocks.zip](https://github.com/Jikoo/EnchantableBlocks/files/2776897/EnchantableBlocks.zip)

I'm not going to do a full release because I believe this should be addressed by CB and individual plugins adding odd recipes.
