### ISSUE TITLE
Bug with Silk Touch and Efficiency (1.17.1)

### ISSUE THREAD

**Issue by aurel85** [Jikoo/EnchantableBlocks#37]
Hi,

With the last version of this plugin (3.0.0) and Paper 1.17.1 there are various problems : 

- Silk touch enchantment no longer works
- Efficiency doesn't work all the time

My players have done more extensive tests, especially with Efficiency : If you interact with the items in the oven, the Efficiency enchantment will resume working normally for a certain period of time. Otherwise there is only the 1st item which functions normally, then the speed is no longer accelerated. Therefore if the oven is fed automatically by hoppers for example there is no problem.

Thank you in advance.

**Comment by Jikoo** [comment]
I love Paper's efficiency improvements, but I really wish they'd stop breaking the Spigot API so frequently. Guess I'll have to poke through recent patches to find the problem. Do you know specifically what Paper upgrade things broke on?

**Comment by aurel85** [comment]
I updated on my server recently so I upgraded from 1.16.5 to Paper 1.17.1 version 143 (and haven't updated since) so I'm not sure when exactly the problem was caused sorry

**Comment by Jikoo** [comment]
Gotcha, no worries.

**Comment by Jikoo** [comment]
Okay, this is 2 separate bugs.

Efficiency isn't being triggered because it appears that the events involved in furnace handling have changed a bit in firing frequency. There's a new 1.17 furnace event that I should be able to use to fix that.

Silk touch isn't working specifically only in blast furnaces and smokers because it appears that the recipe handling for them has changed. That means that EB attempts to unpause the furnace, nothing happens because the recipe "isn't valid," and then MC burns another fuel because the furnace isn't lit. Then after each smelt, there's "no valid recipe" so the furnace immediately pauses. In the end, it consumes 1 fuel per smelt minimum. That might be difficult and I don't have the time to track it down right now, but at least I know where to start.

unrelated: oh my god the new Paper warning about sysout usage is so incredibly annoying while trying to debug, holy heck

**Comment by Jikoo** [comment]
You can get a dev build [here](https://ci.appveyor.com/project/Jikoo/enchantableblocks/build/artifacts). Silk still isn't working perfectly - updates aren't being triggered that should be, so it only seems to trip when there's an actual valid recipe ready to go including fuel, but everything else is fine and at least silk doesn't burn a fuel for every single thing it smelts now :V

**Comment by aurel85** [comment]
I tested and everything you fixed is working, thanks a lot !
