### ISSUE TITLE
Raw ores does not work with fortune

### ISSUE THREAD

**Issue by NeonDerg** [Jikoo/EnchantableBlocks#43]
What the title says. In 1.17 raw ores don't work with the fortune enchant.

**Comment by Kryniowesegryderiusz** [comment]
Did you get it work somehow?

**Comment by Jikoo** [comment]
Presumably they edited the fortune blacklist. Note that you may need to regenerate your configuration for it to appear in the correct location. Raw ores are in the default blacklist due to the potential for double dipping with fortune. Only silk touched ores guarantee that no double dipping can occur.
