### ISSUE TITLE
Problem with anvil costs

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [Jikoo/EnchantableBlocks#52]
Hi, I've problem that after rebuilding anvils system RepairCosts of merging in anvil enchanted furnaces with furnaces or furnaces with enchanted books increased significantly. Is there a way to change, how furnace is interpreted by anvil cost system?

Ex.
If i merge:
1. diamond_pickaxe + book (from gamemode) eff III = diamond_pickaxe eff III
2. diamond_pickaxe eff III + book eff III = diamond_pickaxe eff IV
3. diamond_pickaxe eff IV + diamond_pickaxe eff IV (both made as above) = diamond_pickaxe eff V
At the end RepairCost nbt of diamond_pickaxe eff V is **7**

If I make same thing with furnace instead of diamond_pickaxe repair Cost is **19**.

Can I change it to work ex. like diamond pickaxe?

**Comment by Jikoo** [comment]
Hm, looks like either I misunderstood how the repair cost tag is used or they changed it again.

No, you can't configure it, but EB does vary from vanilla in that regard, so that does need to be fixed.

**Comment by Kryniowesegryderiusz** [comment]
I've made some tests, and maybe them would help you:

1. According to https://minecraft.fandom.com/wiki/Anvil_mechanics first repair cost after mering should start from 1, and in furnaces are starting from 3. Next stages are accortingly pickaxe 3, and furnaces 7. Everyting is falling apart more in further levels, as after 7 should be 15, and there is 19 in EB. 

2. According to my research and checks in minecraft vanilla anvils only possible costs are: 0,1,3,7,15,31  (RepairCost = 2^(Anvil use count) - 1

- So if first item in anvil menu has RepairCost 1 and is merged with basically anything, it gets RepairCost 3, then if its merged again 7, then with next merge 15 and so on.

- if first item is beeing renamed cost of that action is RepairCost +1, but it doesnt affect nbtdata of item (that part of EB works properly)

- item repair does not affect EB Furnaces, but basically is like rename, but +2

**Comment by Jikoo** [comment]
While I appreciate that you looked into it, the wiki is very much user-aimed. There's good information in it, but it's very scattered and full of fluff. For instance, they manually list every enchantment instead of mentioning that enchantment costs are tied directly to rarity and enchantments from enchanted books cost half, minimum 1, of what a normal enchantment at that rarity costs.

The problem is that EB is rolling the additional costs into the base repair cost. While it's a "simple" fix, this is a good excuse to split the anvil and enchantment system out of EB into a separate utility project and clean it up a lot more. EB will still bundle the library, it'll just be more easily accessible for other projects.

If you are interested in the real vanilla mechanics:
```text
get base item from slot 0

if base item is air
  stop and return empty result

get result item by cloning base item
get addition item from slot 1

get existing enchantments from result item

get start cost (base repair cost + addition repair cost if present)
additional cost is 0

if addition item is not air
  if the addition item is used in material repair
    do material repair:
      restore 1/4 max durability per material
      increase additional cost by 1 per material

  otherwise, if the addition item is not used in material repair

    if base item is not identical to addition item and addition item is not an enchanted book
      stop and return empty result

    if base item is identical to addition item and base item has durability
      add durability from addition item + 12% bonus durability to result
      increase additional cost by 2

    combine enchantments
      for every enchantment on the addition item
        new level is either:
          if existing and addition levels match
            addition level + 1
          otherwise
            max of existing and addition levels

        if base item is incompatible with enchantment (existing enchantment conflict or wrong tool type) and user is not in creative
          increase additional cost by 1
          proceed to next enchantment

        cap enchantment to max level for enchantment
        add enchantment to resulting enchantments

        if additional item is an enchanted book
          increase cost by max of rarity value / 2 or 1
        otherwise increase cost by rarity value

        if base item stack size is greater than 1
          set additional cost to 40 (note: this is a hardcoded 40, not anvil max cost!)

      if enchantments exist on addition but none are compatible
        stop and return empty result

if the name of the item has changed
  add 1 to additional cost
  set a flag noting that item name has changed

set cost to start cost + additional cost
if additional cost is less than 0
  stop and return empty result

if the operation is a rename only and cost is greater than max cost
  set cost to max cost - 1 (39 by default)

if the cost is greater than or equal to the max cost
  stop and return empty result


set result anvil repair cost to max of base and addition (if present) repair costs

if not rename only
    multiply result anvil repair cost by 2 and add 1
```

A notable fun potential bug with vanilla anvils:
If you're using a stack increaser and uncapped anvil level and happen to enchant multiple things at once with vanilla code, the additional cost is hardcoded to be 40, the default vanilla anvil limit. That means you can actually enchant as many things as you can stack with a single operation for a fixed level cost. I assume it was supposed to be a "creative mode only" thing, but it doesn't quite hit the mark with plugins.

**Comment by Jikoo** [comment]
I've pushed out the start of [PlanarEnchanting](https://github.com/Jikoo/PlanarEnchanting), splitting the enchantment details out of this project in caee601ac4f0b30ab104d419dec68a4ed0929cfa. The new system is pretty similar but is a lot more comprehensible and should not suffer the same flaw the old one did. This should be resolved, but I'm going to leave it open until I migrate the enchanting table functionality.

**Comment by Jikoo** [comment]
https://github.com/Jikoo/EnchantableBlocks/releases/tag/4.0.0
