### ISSUE TITLE
Options to enable / disable use of furnace / blasting furnace / smoker. 

### ISSUE THREAD

**Issue by aaa8881** [Jikoo/EnchantableBlocks#56]
I found you're putting those three materials together in a set - so this is not possible to only allow furnace to be affected by EnchantableBlock while blasting furnace and smoker are not.

Can you separate them and possibly make it configurable via config? 

+ do you have personal contact like discord to reach? I've got few things to discuss.

**Comment by Jikoo** [comment]
I get that per-material configuration might be nice, but that adds a lot of configuration complexity your average user will not be interested in dealing with. If you particularly want a separate handler for those two materials, you can write an addon and register your own EnchantableBlock implementation for those after EnchantableBlocks enables. It's relatively simple, but not something I am interested in including out of the box.

**Comment by Jikoo** [comment]
Re: Discord
Let me preface this by saying that this is a boilerplate reply and I don't mean any offense or personal attack by it.

I do not offer support via any form of instant messaging.
* Instant messaging gets you a lower quality reply.
  * Replying to several lines of content a couple hours after it is posted is much more difficult when using an IM platform.
  * Due to my own limited time, my response speed to IMs is just as slow as on forums.
  * I read things before I have enough free time to formulate a reply. For email/forums/issue trackers this is fine, but unfortunately, for IM it's a nasty habit. Because there's no way for me to mark messages as unread, I sometimes forget the message exists and never reply at all.
* Instant messaging encourages lower quality interaction.
  * People take the easy route. Why research when they can ask me a question and I'll research it for them?
  * There's social pressure for me to reply faster without properly researching issues.
  * People feel entitled to support when I'm online. This hobby becomes a lot less fun (which in turn only slows down my support) when people demand to know exactly what I'm doing.
* Instant messaging produces fewer useful public resources.
  * IM encourages repeat/duplicate questions because the information is harder (or impossible, depending on settings) to find.

Tl;dr: Yes, I do have Discord, but I don't give it out. If you do really need to contact me privately, I read DMs on Spigot/Bukkit and emails, but for development stuff I prefer to be either tagged in a thread or mentioned in an issue if my input is desired.
