### ISSUE TITLE
Furnaces duplicate upon breaking with EcoEnchants

### ISSUE THREAD

**Issue by Complex1t** [Jikoo/EnchantableBlocks#61]
Upon breaking enchanted furnaces, there is an extra furnace that drops. This seems to be occurring due to some conflict with EcoEnchants, as it does not occur without it installed. [Here's a video.](https://i.imgur.com/BHClhso.mp4)

Paper 1.19-39

EnchantableBlocks 4.0.0
eco 6.37.1
[EcoEnchants 8.93.0](https://github.com/Auxilor/EcoEnchants)
ProtocolLib Build 569

**Comment by Jikoo** [comment]
And the pickaxe is unenchanted? I think unfortunately we're going to need @WillFP's help here - there are approximately a bazillion EcoEnchants enchantments and I'm not familiar with the code. Based on what little I did trace through, EcoEnchants should be ignoring events for unenchanted equipment, so I'm not sure why you're seeing this.

I'll detail how EB handles block drops in case it helps:
On uncancelled block break, EB fetches the ItemStack used to create the EnchantableBlock at the location.
If the item doesn't exist, the block has been set to air, or the event won't drop items for various reasons, EB does not handle it further.
EB attempts to fetch the expected normal drop by getting drops for the player's current tool. This should be the block itself and then (only on Paper) the block's inventory contents.
EB stores the expected drop bound to the block location.

On BlockDropItemEvent, EB checks for a pending drop at that location.
If it exists, EB attempts to remove the expected unenchanted drop. This is where I assume the issue is occurring - does EcoEnchants add PDC entries or something that would cause the ItemStack to not be identical to the expected one?
EB then drops the item used to create the original EnchantableBlock without an additional BlockDropItemEvent.
<br>
This is all because of a Paper inconsistency. On Spigot, the drops are exclusively the actual block drop. On Paper, the drops list includes the inventory contents. It makes sense, but it's a horrendous pain in the butt.
The goal is to not cancel the original BlockBreakEvent because that plays hell with logging plugins, which in turn yields people unhappy that they can't see who took the really nice furnace. I know why logging plugins listen on monitor priority, but it's really inconvenient that they usually still ignore cancelled break events when the block has been set to air - pretty safe to assume some plugin is handling the break specially.
The API is also kinda lacking in this area - you can remove block drops, but you [cannot add your own](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/BlockDropItemEvent.html#getItems()). I assume it's because Spigot is trying to create a minimal diff (the items are probably already added to the world, so allowing plugins to add new items would require them to do a lot more work) but it really sucks for plugins trying to modify block drops.

**Comment by Jikoo** [comment]
I think I can improve my handling of this, but it would probably be a performance increase and not actually solve incompatibilities with EcoEnchants.

**Comment by Jikoo** [comment]
EB fires its own BlockDropItemEvent instead of relying on finding and removing an existing matching drop as of 25c86f1f272fce8083327488f757126406820dd7.

As the furnace is not actually duplicated (the "dupe" isn't enchanted) and I don't believe I can do anything better to support other plugins here, I'm not overly concerned about this. If you still see a spare furnace and that is a dealbreaker for you, you're going to need to get EcoEnchants people to actually weigh in.
